version: '3.5'

services:
  nest_api:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "4000:4000"
    environment:
      POSTGRES_HOST: postgres
    volumes:
      - ./src:/app/api/src/
    links:
      - postgres
    depends_on:
      - postgres
    restart: always
    command: sleep 10m

  test_nest_api:
    build:
      dockerfile: ./test/Dockerfile
    ports:
      - "8080:8080"
    links:
      - nest_api
    depends_on:
      - postgres
#    restart: always
    command: npm run test

  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
      POSTGRES_DB: music_service
    image: postgres:alpine3.16
    restart: always
