version: '3.5'

services:
  nest_api:
    build:
      dockerfile: Dockerfile
      context: ./
    env_file:
      - ./.env
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      POSTGRES_HOST: postgres
    volumes:
      - ./src:/app/api/src/
      - ./node_modules:/app/api/node_modules
    links:
      - postgres
    depends_on:
      - postgres
    restart: always
    command: npm run start:dev

  test_nest_api:
    build:
      dockerfile: ./test/Dockerfile
    ports:
      - "${TEST_API_PORT}:${TEST_API_PORT}"
    links:
      - nest_api
    depends_on:
      - postgres
    volumes:
      - ./node_modules:/test/node_modules
    command: npm run test

  postgres:
    build:
      dockerfile: ./db/Dockerfile
    env_file:
      - ./.env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    restart: always
